services:
  hedgecast:
    build: 
      context: .
      args:
        # This injects the key into the build process so your code sees it
        - API_KEY=${API_KEY}
    container_name: hedgecast-news
    restart: always
    ports:
      - "3010:80"
    networks:
      - app-network
    environment:
      - N8N_URL=http://n8n:5678/webhook/rss-proxy
      - GEMINI_API_KEY=${API_KEY}

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5679:5678"
    networks:
      - app-network
    volumes:
      - n8n_data:/home/node/.n8n

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data:
