name: hedgecast-news

services:
  web:
    image: hedgecast-news:latest
    container_name: hedgecast-news-container
    build:
      context: .
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "3010:80"
    restart: always
