services:
  hedgecast:
    build: .
    container_name: hedgecast-news
    restart: always
    ports:
      - "3010:80" # This maps host port 3010 to container port 80
    networks:
      - app-network
    environment:
      - N8N_URL=http://n8n:5678/webhook/rss-proxy

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5679:5678"
    networks:
      - app-network
    volumes:
      - n8n_data:/home/node/.n8n

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data:
